# Generated by Django 3.2.8 on 2021-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('street', models.TextField(max_length=50)),
                ('number_street', models.IntegerField()),
                ('neighborhood', models.TextField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.FloatField()),
                ('evening', models.FloatField()),
                ('night', models.FloatField()),
                ('weekend', models.FloatField()),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.TextField(max_length=50)),
                ('slug_name', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('limit_image', models.PositiveIntegerField(default=20)),
                ('reputation', models.FloatField(default=5.0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_lots.address')),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
            },
        ),
    ]
