# Generated by Django 2.2.24 on 2021-10-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.FloatField()),
                ('evening', models.FloatField()),
                ('night', models.FloatField()),
                ('weekend', models.FloatField()),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField()),
                ('description', models.TextField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('limit_image', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lots.Price')),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
            },
        ),
    ]
