# Generated by Django 3.2.8 on 2021-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('parking_lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='parking',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lots.price'),
        ),
    ]
