# Generated by Django 2.2.24 on 2021-10-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('street', models.TextField(max_length=50)),
                ('number_street', models.IntegerField()),
                ('neighbothood', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=254)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresss',
            },
        ),
        migrations.AlterField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='parking',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_lots.Address'),
        ),
    ]
