# Generated by Django 3.2.8 on 2021-10-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0002_auto_20211006_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='parking',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='parking',
            name='limit_image',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='parking',
            name='slug_name',
            field=models.SlugField(unique=True),
        ),
    ]
