# Generated by Django 3.2.8 on 2021-10-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0003_auto_20211007_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
