# Generated by Django 3.2.8 on 2021-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0004_alter_address_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='reputation',
            field=models.FloatField(default=5.0),
        ),
    ]
