# Generated by Django 3.2.8 on 2021-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0006_image_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
