# Generated by Django 3.2.8 on 2021-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0007_parking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
