# Generated by Django 3.2.8 on 2021-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0008_alter_parking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='parking',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='parking',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
