# Generated by Django 3.2.8 on 2021-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0009_auto_20211007_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
