# Generated by Django 3.2.8 on 2021-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lots', '0002_initial'),
        ('users', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vehicle'),
        ),
        migrations.AddField(
            model_name='place',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lots.parking'),
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.type'),
        ),
    ]
