# Generated by Django 2.2.24 on 2021-10-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lots', '0002_auto_20211006_0321'),
        ('users', '0002_vehicle'),
        ('reservations', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('final_timestamp', models.DateTimeField()),
                ('is_reserved', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('net_cost', models.FloatField()),
                ('is_paid', models.FloatField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lots.Parking')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vehicle')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
