# Generated by Django 3.2.8 on 2021-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20211006_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_paid',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='net_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='type',
            name='verbose_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
