# Generated by Django 3.2.8 on 2021-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='remaining_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='reserved_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='used_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
