# Generated by Django 2.2.24 on 2021-10-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_place_status'),
        ('reservations', '0010_auto_20211008_0415'),
    ]

    operations = [
    ]
