# Generated by Django 3.2.8 on 2021-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211006_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
