# Generated by Django 3.2.8 on 2021-10-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211007_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(default=5.0),
        ),
    ]
