# Generated by Django 3.2.8 on 2021-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211007_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
    ]
