# Generated by Django 3.2.8 on 2021-10-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211007_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/images/', verbose_name='vehicle image'),
        ),
    ]
